Document: maven-dependencies
Title: Debian maven-dependencies Manual
Author: <insert document author here>
Abstract: This manual describes what maven-dependencies is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/maven-dependencies/maven-dependencies.sgml.gz

Format: postscript
Files: /usr/share/doc/maven-dependencies/maven-dependencies.ps.gz

Format: text
Files: /usr/share/doc/maven-dependencies/maven-dependencies.text.gz

Format: HTML
Index: /usr/share/doc/maven-dependencies/html/index.html
Files: /usr/share/doc/maven-dependencies/html/*.html
